site_name: 'py.gpt.prompt'
repo_url: 'https://github.com/teleprint-me/py.gpt.prompt'
repo_name: 'py.gpt.prompt'
edit_uri: 'tree/main/docs'

theme:
  name: 'material'
  locale: en
  static_templates:
    - sitemap.html
  include_sidebar: false

plugins:
  - mkdocstrings
  - search

watch:
  - pygptprompt

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences