[tool.poetry]
name = "py-gpt-prompt"
version = "0.0.4"
description = "Interface with OpenAI REST API to automate GPT via prompting."
authors = ["teleprint-me <77757836+teleprint-me@users.noreply.github.com>"]
license = "AGPL"
readme = "README.md"
packages = [{include = "py"}]
keywords = ["OpenAI", "GPT", "Python", "Prompt", "Automation", "API"]

[tool.poetry.dependencies]
python = "^3.11"
requests = "^2.31.0"
python-dotenv = "^1.0.0"
tiktoken = "^0.4.0"
prompt-toolkit = "^3.0.38"
peewee = "^3.16.2"
langchain = "^0.0.169"
beautifulsoup4 = "^4.12.2"
feedparser = "^6.0.10"
html2text = "^2020.1.16"
selenium = "^4.9.1"

[tool.poetry.group.dev.dependencies]
flake8 = "^6.0.0"
black = "^23.3.0"
isort = "^5.12.0"
pytest = "^7.3.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
