[tool.poetry]
name = "pygptprompt"
version = "0.0.9"
description = "A Context Window Management System for automating prompting with Chat Models."
authors = ["Austin Berrio aberrio@teleprint.me"]
license = "AGPL"
readme = "README.md"
keywords = ["OpenAI", "GPT", "Python", "Prompt", "Automation", "API"]

[tool.poetry.dependencies]
python = "^3.11"
click = "^8.1.3"
python-dotenv = "^1.0.0"
python-magic = "^0.4.27"
requests = "^2.31.0"
beautifulsoup4 = "^4.12.2"
feedparser = "^6.0.10"
html2text = "^2020.1.16"
prompt-toolkit = "^3.0.38"
selenium = "^4.9.1"
tiktoken = "^0.4.0"
chromadb = "^0.3.26"
huggingface_hub = "^0.15.1"
langchain = "^0.0.219"
llama-cpp-python = "0.1.67"

[tool.poetry.group.dev.dependencies]
pre_commit = "^3.3.3"
pyupgrade = "^3.7.0"
pynvim = "^0.4.3"
pytest = "^7.3.1"
black = "^23.3.0"
isort = "^5.12.0"
flake8 = "^6.0.0"
build = "^0.10.0"

[tool.build]
packages = [
  { include = "pygptprompt" }
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
