#
# NOTE: SciPy Vulnerability
# The Python version must be constrained in order to resolve this issue.
#
# NOTE: Resolve PyTorch dependency
# This is the most satisfying solution for now and will default to CPU as a result.
# poetry source add -p explicit pytorch https://download.pytorch.org/whl/cpu
# poetry add --source pytorch torch torchvision
#
# NOTE: Missing Shared Objects with PyTorch
# Use `pip install torch` to resolve platform specific issues.
# The missing shared objects will be installed as a result.
# https://stackoverflow.com/questions/59158044/poetry-and-pytorch
# https://github.com/python-poetry/poetry/issues/2247
# https://pytorch.org/get-started/locally/
#
# NOTE: PyTorch Workaround is to manually install using pip
# CPU:
# pip3 install torch --index-url https://download.pytorch.org/whl/cpu
#
# ROCm:
# pip3 install torch --index-url https://download.pytorch.org/whl/rocm5.4.2
#
# Nvidia: CUDA wheel is default:
# pip3 install torch
#
[tool.poetry]
name = "pygptprompt"
version = "0.0.20"
description = "A Context Window Management System for automating prompting with Chat Models."
authors = ["Austin Berrio <aberrio@teleprint.me>"]
license = "AGPL"
readme = "README.md"
keywords = ["OpenAI", "GPT", "Python", "Prompt", "Automation", "API"]

[tool.poetry.dependencies]
python = ">=3.11,<3.12"
click = "^8.1.7"
python-dotenv = "^1.0.0"
python-magic = "^0.4.27"
numpy = "^1.26.0"
requests = "^2.31.0"
beautifulsoup4 = "^4.12.2"
feedparser = "^6.0.10"
html2text = "^2020.1.16"
prompt-toolkit = "^3.0.39"
selenium = "^4.12.0"
pyopencl = "^2023.1.2"
opencv-python = "^4.8.0.76"
pytesseract = "^0.3.10"
fairscale = "^0.4.13"
sentencepiece = "^0.1.99"
nltk = "^3.8.1"
spacy = "^3.6.1"
python-poppler = "^0.4.1"
huggingface_hub = "^0.17.1"
chromadb = "^0.4.10"
llama-cpp-python = "^0.2.6"
tiktoken = "^0.5.1"
openai = {extras = ["embeddings"], version = "^0.28.0"}
scipy = "1.11.2"
gguf = "^0.3.2"
torch = {version = "^2.0.1+cpu", source = "pytorch"}
rich = "^13.5.2"
inquirer = "^3.1.3"

[tool.poetry.group.dev.dependencies]
pre_commit = "^3.4.0"
pyupgrade = "^3.11.0"
pynvim = "^0.4.3"
pytest = "^7.4.2"
black = "^23.9.1"
isort = "^5.12.0"
flake8 = "^6.1.0"
build = "^1.0.3"
mkdocs = "^1.5.2"
mkdocstrings = {version = "^0.23.0", extras = ["python"]}
mkdocs-material = "^9.3.1"
ipykernel = "^6.25.2"  # VSCode requires the kernel
# jupyter = "^1.0.0"  # Only install if you need it

[[tool.poetry.source]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cpu"
priority = "explicit"

[tool.pytest.ini_options]
markers = [
    "slow: run slow tests",
    "private: test private endpoints",
]

[tool.build]
packages = [
  { include = "pygptprompt" }
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
